title: "(Add your project name here!)"
labels: ["Ideas"]
body:
  - type: textarea
    id: authors
    attributes:
      label: Project Author(s)
      description: "Who is proposing this project? If multiple people are involved, please list all names."
      value: |
      render: markdown
    validations:
      required: true
  - type: textarea
    id: description_short
    attributes:
      label: Short Description
      description: "Describe your project in ONE sentence. That can be challenging - almost like an 'elevator pitch'!"
      value: |
      render: markdown
    validations:
      required: true
  - type: textarea
    id: description_long
    attributes:
      label: Long Description
      description: "Describe your project in more detail. What are the goals? What are the deliverables? What are the potential challenges?"
      value: |
      render: markdown
    validations:
      required: true
  - type: dropdown
    id: expertise_bw
    attributes:
      label: How do the authors rate their expertise in Brightway (0-10)?
      options:
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
        - 9
        - 10
      validations:
        required: true
  - type: dropdown
    id: expertise_python
    attributes:
      label: How do the authors rate their expertise in Python (0-10)?
      options:
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
        - 9
        - 10
    validations:
      required: true