title: "(Add your project name here!)"
labels: ["Ideas"]
body:
  - type: input
    id: authors
    attributes:
      label: Project Author(s)
      description: "Who is proposing this project? If multiple people are involved, please list all names."
      value:
        ...
    validations:
      required: true
  - type: input
    id: description_short
    attributes:
      label: Short Description
      description: "Describe your project in ONE sentence. That can be challenging - almost like an 'elevator pitch'!"
      value: |
        ...
    validations:
      required: true
  - type: textarea
    id: description_long
    attributes:
      label: Long Description
      description: "Describe your project in more detail. What are the goals? What are the deliverables? What are the potential challenges?"
      placeholder: "We will build a WORLD MODEL 🌎 Mwhahaha!"
    validations:
      required: true
  - type: textarea
    id: image
    attributes:
      label: Illustration
      description: "Do you have an image or document to illustrate the project? Please add it here!"
    validations:
      required: false
  - type: dropdown
    id: expertise_bw
    attributes:
      label: How do the authors rate their expertise in Brightway (0-10)?
      options:
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
        - 9
        - 10
    validations:
      required: true
  - type: dropdown
    id: expertise_python
    attributes:
      label: How do the authors rate their expertise in Python (0-10)?
      options:
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
        - 9
        - 10
    validations:
      required: true